import { useRef,useState } from 'react';
import type { GameState } from './types';
import { CROPS,formatNumber,plotYield,plotCost,upgradeCost,workerCost,tractorCapacity,tractorDuration,tractorUpgradeCost,truckCapacity,truckUpgradeCost } from './game';
import { DEPOT,parcelLayout,routeToDepot,pointOnRoute } from './layout';
import './FieldWorld.css';
type Props={game:GameState;onHarvest:(i:number)=>void;onUpgrade:(i:number)=>void;onHire:(i:number)=>void;onExpand:()=>void;onTractorUpgrade:(kind:'capacity'|'speed')=>void;onTruckUpgrade:()=>void};
function Worker({x,y,carrying,moving}:{x:number;y:number;carrying:boolean;moving:boolean}){return <g transform={`translate(${x} ${y})`} className="tile-worker"><ellipse cy="15" rx="13" ry="5" fill="#29473425"/><g className={moving?'worker-step':''}><path d="M-5 6v10M5 6v10" stroke="#405966" strokeWidth="5" strokeLinecap="round"/><rect x="-9" y="-10" width="18" height="20" rx="5" fill="#648c81"/><path d="M-10-6-14 5M10-6 14 5" stroke="#deb487" strokeWidth="4" strokeLinecap="round"/><circle cy="-17" r="8" fill="#efc79b"/><ellipse cy="-22" rx="14" ry="4" fill="#eac57e"/><path d="M-8-23v-5q8-8 16 0v5" fill="#f3d897"/>{carrying&&<g transform="translate(8 2)"><rect width="18" height="15" rx="2" fill="#bb8447" stroke="#efce8d" strokeWidth="2"/><circle cx="5" cy="0" r="4" fill="#dc6044"/><circle cx="13" cy="0" r="4" fill="#e5734c"/></g>}</g></g>}
function Vehicle({x,y,truck,load,vertical=false,reverse=false}:{x:number;y:number;truck?:boolean;load:number;vertical?:boolean;reverse?:boolean}){return <g transform={`translate(${x} ${y}) rotate(${vertical?(reverse?-90:90):reverse?180:0})`}><ellipse cy="7" rx="53" ry="23" fill="#294d3225"/>{[-31,24].map(a=><g key={a}><rect x={a-7} y="-27" width="14" height="12" rx="4" fill="#354c42"/><rect x={a-7} y="15" width="14" height="12" rx="4" fill="#354c42"/></g>)}<rect x="-48" y="-19" width="52" height="38" rx="4" fill={truck?'#f0eed9':'#c99955'} stroke={truck?'#819c91':'#956d3d'} strokeWidth="3"/>{!truck&&load>0&&<rect x="-43" y="-14" width={42*Math.min(1,load)} height="28" rx="3" fill="#dc7952"/>}<rect x="4" y="-20" width="42" height="40" rx="7" fill={truck?'#528b9a':'#d69b42'}/><rect x="13" y="-15" width="15" height="30" rx="3" fill="#b7dad3"/><rect x="36" y="-12" width="6" height="24" rx="2" fill={truck?'#397081':'#b87532'}/>{truck&&<text x="-22" y="4" fontSize="10" textAnchor="middle" fill="#64856b" fontWeight="800">FİLİZ</text>}</g>}
export default function FieldWorld({game,onHarvest,onUpgrade,onHire,onExpand,onTractorUpgrade,onTruckUpgrade}:Props){
 const crop=CROPS.find(c=>c.id===game.selectedCrop)!,farm=game.farms[crop.id];
 const [zoom,setZoom]=useState(farm.plots.length>8?1.8:1),[pan,setPan]=useState({x:0,y:0});
 const drag=useRef<{x:number;y:number;px:number;py:number}|null>(null);
 const count=Math.min(36,farm.plots.length+1),slots=Array.from({length:count},(_,i)=>parcelLayout(i));
 const width=Math.max(1120,...slots.map(p=>p.x+240)),height=Math.max(940,...slots.map(p=>p.y+280));
 const cam={x:pan.x,y:pan.y,w:width/zoom,h:height/zoom};
 const route=routeToDepot(game.tractor.plotIndex),t=game.tractor;
 const progress=t.phase==='outbound'?t.progress:t.phase==='returning'?1-t.progress:0;
 const pos=pointOnRoute(route,progress),ahead=pointOnRoute(route,Math.min(1,progress+.005));
 const truckProgress=game.truck.phase==='outbound'?game.truck.progress:game.truck.phase==='returning'?1-game.truck.progress:0;
 const truckPos={x:DEPOT.x+120+truckProgress*(width-DEPOT.x-230),y:DEPOT.y};
 const totalStock=CROPS.reduce((n,c)=>n+game.farms[c.id].stock,0);
 return <div className="tile-world"><svg className="tile-canvas" viewBox={`${cam.x} ${cam.y} ${cam.w} ${cam.h}`} aria-label={`${crop.name} çiftliği; yollara bağlı ${farm.plots.length} parsel`} onPointerDown={e=>{if((e.target as Element).closest('foreignObject'))return;drag.current={x:e.clientX,y:e.clientY,px:pan.x,py:pan.y};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(!drag.current)return;const bounds=e.currentTarget.getBoundingClientRect();const f=Math.max(cam.w/bounds.width,cam.h/bounds.height);setPan({x:drag.current.px-(e.clientX-drag.current.x)*f,y:drag.current.py-(e.clientY-drag.current.y)*f});}} onPointerUp={()=>drag.current=null} onPointerCancel={()=>drag.current=null}>
  <defs><pattern id="grass-specks" width="140" height="120" patternUnits="userSpaceOnUse"><path d="M20 35l3 5 3-5M103 85l3 6 4-6" fill="none" stroke="#8ab268" strokeWidth="2" opacity=".35"/></pattern><linearGradient id="tile-grass" x2="0" y2="1"><stop stopColor="#b7d397"/><stop offset="1" stopColor="#a1c47d"/></linearGradient></defs>
  <rect x="-5000" y="-5000" width="20000" height="20000" fill="url(#tile-grass)"/><rect x="-5000" y="-5000" width="20000" height="20000" fill="url(#grass-specks)"/>
  {/* Road tiles connect a fixed vertical spine to each two-sided field street. */}
  <path d={`M${width+100} ${DEPOT.y}H${DEPOT.x}V${Math.max(...slots.map(p=>p.roadY))+70}`} fill="none" stroke="#c6ae7a" strokeWidth="76" strokeLinejoin="round" strokeLinecap="round"/>
  <path d={`M${width+100} ${DEPOT.y}H${DEPOT.x}V${Math.max(...slots.map(p=>p.roadY))+70}`} fill="none" stroke="#e4cb96" strokeWidth="66" strokeLinejoin="round" strokeLinecap="round"/>
  {[...new Set(slots.map(p=>p.roadY))].map(y=><g key={y}><path d={`M160 ${y}H${width-60}`} stroke="#c6ae7a" strokeWidth="76" strokeLinecap="round"/><path d={`M160 ${y}H${width-60}`} stroke="#e4cb96" strokeWidth="66" strokeLinecap="round"/><path d={`M180 ${y}H${width-75}`} stroke="#f5e5bc" strokeWidth="3" strokeDasharray="12 24"/></g>)}
  <path d={`M160 ${DEPOT.y+45}V${Math.max(...slots.map(p=>p.roadY))+60}`} stroke="#f5e5bc" strokeWidth="3" strokeDasharray="12 24"/>
  <g transform="translate(55 25)"><rect x="7" y="40" width="155" height="98" rx="4" fill="#b8a786" opacity=".25"/><rect x="0" y="35" width="155" height="95" rx="4" fill="#ead9b1"/><path d="M-12 40 76 0 168 40v17H-12Z" fill="#b9704b"/><path d="M76 0 168 40H-12Z" fill="#d39465"/><rect x="62" y="76" width="39" height="54" fill="#877254"/><path d="M65 80 97 125M97 80 65 125" stroke="#c8b18a" strokeWidth="3"/><rect x="17" y="73" width="24" height="26" fill="#8cb7b1" stroke="#fff1cc" strokeWidth="4"/><rect x="0" y="134" width="155" height="25" rx="8" fill="#fff6d6"/><text x="78" y="151" textAnchor="middle" fontSize="12" fill="#5b6645" fontWeight="800">ÇİFTLİK DEPOSU</text></g>
  <text x={width-95} y="109" textAnchor="end" className="tile-label">ŞEHİR PAZARI →</text>
  <foreignObject x="285" y="25" width="750" height="103"><div className="fleet-toolbar"><div><small>DEPODA</small><strong>{formatNumber(totalStock)} ürün</strong><small>Traktör: {CROPS.find(c=>c.id===t.cropId)?.name}</small></div><button disabled={t.capacityLevel>=1000||game.coins<tractorUpgradeCost(game,'capacity')} onClick={()=>onTractorUpgrade('capacity')}>Traktör kasası <b>{formatNumber(tractorCapacity(game))} ürün</b><small>↑ {formatNumber(tractorUpgradeCost(game,'capacity'))} altın</small></button><button disabled={t.speedLevel>=14||game.coins<tractorUpgradeCost(game,'speed')} onClick={()=>onTractorUpgrade('speed')}>Traktör hızı <b>{tractorDuration(game).toFixed(1)} sn</b><small>{t.speedLevel>=14?'MAKS':`↑ ${formatNumber(tractorUpgradeCost(game,'speed'))} altın`}</small></button><button disabled={game.truck.level>=100||game.coins<truckUpgradeCost(game)} onClick={onTruckUpgrade}>Kamyon kasası <b>{formatNumber(truckCapacity(game))} ürün</b><small>↑ {formatNumber(truckUpgradeCost(game))} altın</small></button></div></foreignObject>
  {slots.map((p,i)=>{const plot=farm.plots[i];if(!plot)return <g key={i}><rect x={p.x} y={p.y} width={160} height={160} rx="12" fill="#d3e4a866" stroke="#edf3c8" strokeWidth="3" strokeDasharray="8 7"/><foreignObject x={p.x-6} y={p.y+44} width="172" height="100"><button className="tile-expand" disabled={game.coins<plotCost(game,crop.id)} onClick={onExpand}>＋<b>Yeni 2 × 2 parsel</b><small>{formatNumber(plotCost(game,crop.id))} altın</small></button></foreignObject></g>;
   const workerFrom={x:p.x+82,y:p.y+80},travel=plot.workerPhase==='carrying'?plot.workerProgress:plot.workerPhase==='returning'?1-plot.workerProgress:0;
   return <g key={i} aria-label={`Parsel ${i+1}`}>
    <text x={p.x+80} y={p.y-75} textAnchor="middle" className="tile-label">PARSEL {String(i+1).padStart(2,'0')} · SV. {plot.level}</text>
    <foreignObject x={p.x-20} y={p.y-63} width="200" height="55"><div className="tile-actions"><button aria-label={`Alan ${i+1} geliştir`} disabled={plot.level>=1000||game.coins<upgradeCost(game,crop.id,i)} onClick={()=>onUpgrade(i)}>↑ Geliştir<small>{plot.level>=1000?'MAKS':formatNumber(upgradeCost(game,crop.id,i))+' altın'}</small></button>{plot.worker?<span className="tile-auto">✓ Çiftçi<small>{plot.workerPhase==='idle'?'Bekliyor':plot.workerPhase==='harvesting'?'Topluyor':plot.workerPhase==='carrying'?'Kolilere taşıyor':'Geri dönüyor'}</small></span>:<button aria-label={`Alan ${i+1} çiftçi işe al`} disabled={game.coins<workerCost(game,crop.id,i)} onClick={()=>onHire(i)}>＋ Çiftçi<small>{formatNumber(workerCost(game,crop.id,i))} altın</small></button>}</div></foreignObject>
    <rect x={p.x+3} y={p.y+7} width="160" height="160" rx="9" fill="#6c7e4840"/><rect x={p.x-4} y={p.y-4} width="168" height="168" rx="9" fill="#d7bb86"/>
    {[0,1].flatMap(r=>[0,1].map(c=><g key={`${r}${c}`} transform={`translate(${p.x+c*82} ${p.y+r*82})`}><rect width="77" height="77" rx="4" fill="#79583b"/>{[18,39,60].map(line=><path key={line} d={`M7 ${line}H70`} stroke="#9a7048" strokeWidth="3"/>)}{[0,1,2,3].map(n=><g key={n} transform={`translate(${23+(n%2)*31} ${21+Math.floor(n/2)*32}) scale(${.55+.45*plot.progress})`}><ellipse cy="6" rx="12" ry="7" fill="#3e33262f"/><path d="M0 8V-8M0 1Q-20-13-12-14Q1-15 0 1M0-2Q17-17 14-4Q9 5 0-2" fill="#67924e" stroke="#4e7842" strokeWidth="2"/>{game.selectedCrop==='honey'?<rect x="-9" y="-8" width="18" height="20" rx="5" fill="#dab15d"/>:<><circle cx="-6" cy="4" r="5" fill={plot.ready?crop.color:'#95b866'}/><circle cx="6" cy="0" r="6" fill={plot.ready?crop.color:'#a4bf6d'}/><circle cx="7" cy="-2" r="1.5" fill="#ffe8b8"/></>}</g>)}</g>))}
    <foreignObject x={p.x-9} y={p.y+173} width="178" height="38"><button className={`tile-harvest ${plot.ready?'ready':''}`} disabled={!plot.ready||plot.workerPhase==='harvesting'} onClick={()=>onHarvest(i)}>{plot.ready?`Hasat et · ${formatNumber(plot.ready)}`:`Büyüyor · %${Math.floor(plot.progress*100)}`}</button></foreignObject>
    <g transform={`translate(${p.crate.x} ${p.crate.y})`}><rect x="-34" y="-16" width="68" height="32" rx="6" fill="#c1b083" opacity=".6"/>{[0,1,2].map(n=><g key={n} transform={`translate(${(n-1)*20} 0)`}><rect x="-8" y="-11" width="17" height="22" rx="2" fill={plot.waiting>0?'#b98449':'#c5ac79'} stroke="#f0d39d" strokeWidth="2"/><path d="M-6-3H7M-6 4H7" stroke="#e5c08b"/>{plot.waiting>0&&<circle cy="-11" r="5" fill={crop.color}/>}</g>)}<text y={p.lower?-24:31} textAnchor="middle" className="crate-label">{formatNumber(plot.waiting)} ürün</text></g>
    {plot.worker&&<Worker x={workerFrom.x+(p.crate.x-workerFrom.x)*travel} y={workerFrom.y+(p.crate.y-workerFrom.y)*travel} carrying={plot.carrying>0} moving={plot.workerPhase!=='idle'}/>}
   </g>;
  })}
  {t.cropId===crop.id&&<><Vehicle x={pos.x} y={pos.y} load={t.cargo/tractorCapacity(game)} vertical={Math.abs(ahead.y-pos.y)>Math.abs(ahead.x-pos.x)} reverse={t.phase==='outbound'}/><text x={pos.x} y={pos.y-41} textAnchor="middle" className="vehicle-label">{t.phase==='loading'?'Koli topluyor':t.phase==='outbound'?'Depoya taşıyor':'Tarlaya gidiyor'} · {formatNumber(t.cargo)}</text></>}
  <Vehicle x={truckPos.x} y={truckPos.y} truck load={1} reverse={game.truck.phase==='returning'}/><text x={truckPos.x} y={truckPos.y+48} textAnchor="middle" className="vehicle-label">{game.truck.phase==='loading'?'Kamyon yükleniyor':game.truck.phase==='outbound'?'Pazara gidiyor':'Depoya dönüyor'}</text>
 </svg><div className="world-camera"><button aria-label="Uzaklaştır" onClick={()=>setZoom(z=>Math.max(.5,z-.3))}>−</button><button aria-label="Tüm çiftliği göster" onClick={()=>{setZoom(1);setPan({x:0,y:0})}}>⌖</button><button aria-label="Yakınlaştır" onClick={()=>setZoom(z=>Math.min(8,z+.3))}>+</button></div><span className="world-hint">Sürükle ve keşfet · {farm.plots.length} parsel · Her parsel 2 × 2</span></div>;
}
